#!/bin/bash

# 作为工具的总入口
# 设定和进入当前的环境
#  myenv <command> [options]
#    如果没有 参数，那么找 nearest env。
# 工作命令（function）
#  mysh <command> [options]

# 调试设定
[[ "${TRACE}" ]] && set -x
#set -eo pipefail  # 如果想让函数命令返回其他的值，就不能设置这个。

# 工具本身的环境变量。
export MYENV_TOOL_PATH="$(cd "$(dirname "$0")" && pwd)"
export MYENV_TOOL_SRC_PATH="${MYENV_TOOL_PATH}/src"
export MYENV_TOOL_SRC_COMMON_PATH="${MYENV_TOOL_SRC_PATH}/common"
export MYENV_TOOL_MYENV_PATH="${MYENV_TOOL_SRC_PATH}/myenv"
export MYENV_TOOL_SH_PATH="${MYENV_TOOL_SRC_PATH}/mysh"

# 目前工具支持的最大版本
export MYENV_TOOL_MAX_KIND=1
export MYENV_TOOL_SH_MAX_KIND=1

# 当前的版本
export MYENV_TOOL_CUR_KIND=1
export MYENV_TOOL_SH_CUR_KIND=1

# 加载共通的脚本
source ${MYENV_TOOL_SRC_COMMON_PATH}/loader/loader.sh
myenv_load_scripts ${MYENV_TOOL_SRC_COMMON_PATH}

# 加载启动程序的脚本
myenv_load_scripts ${MYENV_TOOL_MYENV_PATH}/startup "$*"
