#!/bin/bash

# 作为工具的总入口

set -eo pipefail
[[ "${TRACE}" ]] && set -x

export MYSH_DIR="$(cd "$(dirname "$0")" && pwd)"
export MYSH_SRC_DIR="${MYSH_DIR}/src"

if [ $# -eq 0 ]; then
    echo "Please input one action and options."
    exit 1
fi

source $MYSH_SRC_DIR/_common.sh
source $MYSH_SRC_DIR/_help.sh
source $MYSH_SRC_DIR/_list.sh
source $MYSH_SRC_DIR/_set.sh
source $MYSH_SRC_DIR/_run.sh

case "$1" in
    help)
	usage $@
	exit 0;;
    list)
	shift
	grp_list $@
	exit 0;;
    set)
	shift
	grp_set $@
	exit 0;;
    run)
	shift
	grp_run $@
	exit 0;;
    *)
	usage 1>&2 ; exit 1;;
esac

if [ $# -ne 1 ]; then
    echo "Please input one setting name."
    exit 1
fi

export MYSH_COMMON_SETTING="${HOME}/bin/setting/common/setting.sh"
export MYSH_CUR_SETTING="${HOME}/bin/setting/$1/setting.sh"

if [ ! -f $MYSH_CUR_SETTING ]; then
  echo "Cannot find \"setting.sh\" in ~/bin/setting/$1/."
  exit 1
fi

bash --rcfile ${MYSH_SRC_DIR}/shell.sh
