#!/bin/bash

# 独立运行
# 显示一个对话框。

function help()
{
	printf "\nmyenv dialog %s\n"
	printf "  show a dialog\n"
}

# 分析参数
OPTS=`getopt -o h --long help -n "$(basename $0)" -- "$@"`
if [ $? != 0 ]; then
	help
	return 1
fi
eval set -- "$OPTS"

while true ; do
	case "$1" in
		-h|--help)
			help
			shift
			exit 0
			;;
		--)
			shift
			break
			;;
		*)
			help
			shift
			exit 1
			;;
	esac
done

dialog --msgbox test2 10 100
