# parse 之后的共通的启动项目！
# 需要 MYENV_CUR_PATH / MYENV_CUR_NAME

# ${MYENV_CUR_PATH}/.myenv 的宏
export MYENV_CUR_CONFIG_PATH="${MYENV_CUR_PATH}/.myenv"
export MYENV_CUR_CONFIG_KIND_PATH="${MYENV_HOME_CONFIG_PATH}/kind"
export MYENV_CUR_CONFIG_BIN_PATH="${MYENV_CUR_CONFIG_PATH}/bin"
export MYENV_CUR_CONFIG_SOURCE_PATH="${MYENV_CUR_CONFIG_PATH}/source"
export MYENV_CUR_CONFIG_DATA_PATH="${MYENV_CUR_CONFIG_PATH}/data"
